import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import React, {StrictMode} from 'react';
import clsx from 'clsx';

import MenuIcon from '@/components/common/menu-icon';
import Logo from '@/components/common/logo';
import Cart from '@/components/common/cart';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StrictMode >
      <html lang="en">
      <body
        className={`${inter.className}`}
        suppressHydrationWarning={true}
      >
      <header
        className={clsx(
          'mx-auto items-center flex border-amber-900 border-b-2 justify-between w-full p-3')}
      >
        <button
          type="button"
          className={clsx('w-8', 'sm:hidden')}
        >
          <MenuIcon />
        </button >
        <Link
          className="block"
          href="#"
        >
          <Logo />
        </Link >
        <div className="flex gap-5 items-center">
          <nav
            className={clsx('hidden max-w-max', 'sm:inline')}
          >
            <ul className="flex items-baseline justify-around gap-3">
              <li className="">
                <Link
                  href="#"
                  className=""
                >
                  BROWSE MENU
                </Link >
              </li >
              <li className="">
                <Link href="#">
                  RESERVATION
                </Link >
              </li >
              <li className="">
                <Link href="#">
                  LOGIN
                </Link >
              </li >
            </ul >
          </nav >
          <Link
            href={'#'}
            className="w-8"
          >
            <Cart />
          </Link >
        </div>
      </header >
      {children}
      {/*<Modal />*/}
      </body >
      </html >
    </StrictMode >
  );
}
